// Generated by dojo-bindgen on Fri, 31 Jan 2025 10:00:19 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `dojo_starter::models::Direction` enum
public abstract record Direction() : Enum {
    public record Left() : Direction;
    public record Right() : Direction;
    public record Up() : Direction;
    public record Down() : Direction;
}


// Model definition for `dojo_starter::models::DirectionsAvailable` model
public class dojo_starter_DirectionsAvailable : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("directions")]
        public Direction[] directions;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        