// Generated by dojo-bindgen on Fri, 31 Jan 2025 10:00:19 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `dojo_starter::models::Vec2` struct
[Serializable]
public struct Vec2 {
    public uint x;
    public uint y;
}


// Model definition for `dojo_starter::models::Position` model
public class dojo_starter_Position : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("vec")]
        public Vec2 vec;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
        transform.position = Vector3.MoveTowards(transform.position, new Vector3(vec.x, 0, vec.y), 0.1f);
    }
}

        