// Generated by dojo-bindgen on Mon, 8 Jul 2024 11:09:54 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_examples::models::Direction` enum
public abstract record Direction() : Enum {
    public record None() : Direction;
    public record Left() : Direction;
    public record Right() : Direction;
    public record Up() : Direction;
    public record Down() : Direction;
}


namespace dojo_examples {
    // Model definition for `dojo_examples::actions::actions::Moved` model
    public class Moved : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("direction")]
        public Direction direction;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        