// Generated by dojo-bindgen on Mon, 8 Jul 2024 11:09:54 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace dojo_examples {
    // Model definition for `dojo_examples::models::Message` model
    public class Message : ModelInstance {
        [ModelField("identity")]
        public FieldElement identity;

        [ModelField("channel")]
        public FieldElement channel;

        [ModelField("message")]
        public string message;

        [ModelField("salt")]
        public FieldElement salt;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        