// Generated by dojo-bindgen on Fri, 31 Jan 2025 10:00:19 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;

// Type definition for `core::option::Option::<core::integer::u32>` enum
public abstract record Option<A>() : Enum {
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}


// Model definition for `dojo_starter::models::Moves` model
public class dojo_starter_Moves : ModelInstance {
    [ModelField("player")]
        public FieldElement player;

        [ModelField("remaining")]
        public byte remaining;

        [ModelField("last_direction")]
        public Option<Direction> last_direction;

        [ModelField("can_move")]
        public bool can_move;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        