// Generated by dojo-bindgen on Mon, 8 Jul 2024 11:09:54 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace dojo_examples {
    // Model definition for `dojo_examples::models::ServerProfile` model
    public class ServerProfile : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("server_id")]
        public uint server_id;

        [ModelField("name")]
        public string name;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        