// Generated by dojo-bindgen on Mon, 8 Jul 2024 11:09:54 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_examples::models::PlayerItem` struct
[Serializable]
public struct PlayerItem {
    public uint item_id;
    public uint quantity;
}


namespace dojo_examples {
    // Model definition for `dojo_examples::models::PlayerConfig` model
    public class PlayerConfig : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("name")]
        public string name;

        [ModelField("items")]
        public PlayerItem[] items;

        [ModelField("favorite_item")]
        public Option<uint> favorite_item;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        