// Generated by dojo-bindgen on Tue, 2 Apr 2024 22:22:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

// Type definition for `dojo_examples::models::Emote` enum
public enum Emote {
    None,
    Happy,
    Sad,
    Angry,
    Love,
}


// Model definition for `dojo_examples::models::EmoteMessage` model
public class EmoteMessage : ModelInstance {
    [ModelField("identity")]
    public FieldElement identity;

    [ModelField("emote")]
    public Emote emote;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        