// Generated by dojo-bindgen on Tue, 2 Apr 2024 22:22:30 +0000. Do not modify this file manually.
using System;
using System.Linq;
using System.Reflection;
using Dojo;
using Dojo.Starknet;
using Dojo.Torii;
using UnityEngine;

// Type definition for `dojo_examples::models::Emote` enum
public abstract record Emote() {
    public record None() : Emote;
    public record Happy() : Emote;
    public record Sad() : Emote;
    public record Angry() : Emote;
    public record Love() : Emote;

    public static readonly Type[] EmoteTypes = typeof(Emote).GetNestedTypes(BindingFlags.Public)
        .OrderBy(t => t.MetadataToken)
        .ToArray();

    public static int GetIndex(Emote value) {
        return Array.IndexOf(EmoteTypes, value.GetType());
    }
}


// Model definition for `dojo_examples::models::EmoteMessage` model
public class EmoteMessage : ModelInstance
{
    [ModelField("identity")]
    public FieldElement identity;

    [ModelField("emote")]
    public Emote emote;

    MeshRenderer meshRenderer;

    string shortAddress;
    TextMesh textTag;

    // Start is called before the first frame update
    void Start()
    {
        meshRenderer = GetComponentInChildren<MeshRenderer>();

        shortAddress = identity.Hex().Substring(0, 8);

        // create a new GameObject for the text
        GameObject textObject = new GameObject("TextTag");
        textObject.transform.localScale = new Vector3(0.3f, 0.3f, 0.3f);
        textObject.transform.parent = transform;
        textObject.transform.localPosition = new Vector3(-1, 2, 0);


        // add a Text component to the new GameObject
        textTag = textObject.AddComponent<TextMesh>();

        // set the properties of the Text component
        textTag.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        textTag.color = Color.black;
    }

    // Update is called once per frame
    void Update()
    {
        switch (emote)
        {
            case Emote.None:
                meshRenderer.material.color = Color.Lerp(meshRenderer.material.color, Color.white, Time.deltaTime);
                break;
            case Emote.Happy:
                meshRenderer.material.color = Color.Lerp(meshRenderer.material.color, Color.green, Time.deltaTime);
                break;
            case Emote.Sad:
                meshRenderer.material.color = Color.Lerp(meshRenderer.material.color, Color.black, Time.deltaTime);
                break;
            case Emote.Angry:
                meshRenderer.material.color = Color.Lerp(meshRenderer.material.color, Color.red, Time.deltaTime);
                break;
            case Emote.Love:
                meshRenderer.material.color = Color.Lerp(meshRenderer.material.color, Color.magenta, Time.deltaTime);
                break;
        }

        textTag.text = $"{shortAddress}\nFeeling: {emote}";
    }

    public override void OnUpdate(Model model)
    {
        base.OnUpdate(model);
    }
}
