// Generated by dojo-bindgen on Tue, 2 Apr 2024 22:22:30 +0000. Do not modify this file manually.
using System;
using System.Linq;
using System.Reflection;
using Dojo;
using Dojo.Starknet;
using Dojo.Torii;
using UnityEngine;

// Model definition for `dojo_examples::models::EmoteMessage` model
public class Message : ModelInstance
{
    [ModelField("identity")]
    public FieldElement identity;

    [ModelField("message")]
    public string message;
    [ModelField("channel")]
    public FieldElement channel;

    [ModelField("salt")]
    public FieldElement salt;


    MeshRenderer meshRenderer;

    string shortAddress;
    TextMesh textTag;

    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {

    }

    public override void OnUpdate(Model model)
    {
        base.OnUpdate(model);
    }
}
