// Generated by dojo-bindgen on Tue, 2 Apr 2024 22:22:30 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;

// Model definition for `dojo_examples::actions::actions::Moved` model
public class Moved : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("direction")]
    public Direction direction;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}
        