// Generated by dojo-bindgen on Mon, 4 Nov 2024 23:36:28 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `core::option::Option::<core::integer::u32>` enum
public abstract record Option<A>() : Enum {
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}

// Model definition for `dojo_examples::models::Message` model
public class ns_Message : ModelInstance {
    [ModelField("identity")]
    public FieldElement identity;

    [ModelField("channel")]
    public FieldElement channel;

    [ModelField("message")]
    public string message;

    [ModelField("salt")]
    public FieldElement salt;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        