// Generated by dojo-bindgen on Mon, 4 Nov 2024 23:36:28 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_examples::models::PlayerConfigValue` struct
[Serializable]
public struct PlayerConfigValue {
    public string name;
    public PlayerItem[] items;
    public Option<uint> favorite_item;
}

// Type definition for `dojo_examples::models::PlayerItem` struct
[Serializable]
public struct PlayerItem {
    public uint item_id;
    public uint quantity;
    public int score;
}


// Model definition for `dojo_examples::models::PlayerConfig` model
public class ns_PlayerConfig : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("name")]
    public string name;

    [ModelField("items")]
    public PlayerItem[] items;

    [ModelField("favorite_item")]
    public Option<uint> favorite_item;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        