// Generated by dojo-bindgen on Mon, 4 Nov 2024 23:36:28 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_examples::models::ServerProfileValue` struct
[Serializable]
public struct ServerProfileValue {
    public string name;
}


// Model definition for `dojo_examples::models::ServerProfile` model
public class ns_ServerProfile : ModelInstance {
    [ModelField("player")]
    public FieldElement player;

    [ModelField("server_id")]
    public uint server_id;

    [ModelField("name")]
    public string name;

    // Start is called before the first frame update
    void Start() {
    }

    // Update is called once per frame
    void Update() {
    }
}

        