// Generated by dojo-bindgen on Tue, 5 Nov 2024 17:50:16 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;
using BigInteger = System.Numerics.BigInteger;
using UnityEngine;
using Newtonsoft.Json;

// Type definition for `core::integer::u256` struct
[Serializable]
public struct U256 {
    public BigInteger low;
    public BigInteger high;
}


// Model definition for `dojo_examples::models::Test` model
public class ns_Test : ModelInstance {
    [ModelField("ok")]
    public uint ok;

    [ModelField("x")]
    public long x;

    [ModelField("y")]
    public BigInteger y;

    [ModelField("z")]
    public BigInteger z;

    [ModelField("a")]
    public U256 a;

    // Start is called before the first frame update
    void Start() {
        Debug.Log($"ok: {ok}");
        Debug.Log($"x: {x}");
        Debug.Log($"y: {y}");
        Debug.Log($"z: {z}");
        Debug.Log($"a: {JsonConvert.SerializeObject(a)}");
    }

    // Update is called once per frame
    void Update() {
    }
}

        