// Generated by dojo-bindgen on Mon, 3 Jun 2024 17:52:12 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using UnityEngine;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_examples::models::PlayerItem` struct
[Serializable]
public struct PlayerItem
{
    public uint item_id;
    public uint quantity;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
public abstract record Option<A>() : Enum
{
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}

// Model definition for `dojo_examples::models::PlayerConfig` model
public class PlayerConfig : ModelInstance
{
    [ModelField("player")]
    public FieldElement player;

    [ModelField("name")]
    public string name;

    [ModelField("items")]
    public PlayerItem[] items;

    [ModelField("favorite_item")]
    public Option<uint> favorite_item;

    // Start is called before the first frame update
    void Start()
    {
    }

    // Update is called once per frame
    void Update()
    {
    }
}
