// Generated by dojo-bindgen on Mon, 3 Jun 2024 17:52:12 +0000. Do not modify this file manually.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Dojo;
using Dojo.Starknet;
using Dojo.Torii;
using Newtonsoft.Json;
using UnityEngine;

// Type definition for `dojo_examples::models::PlayerItem` struct
[Serializable]
public struct PlayerItem
{
    public uint item_id;
    public uint quantity;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
public abstract record Option<A>()
{
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;

    private static readonly IReadOnlyDictionary<Type, int> TypeIndices = typeof(Option<A>)
        .GetNestedTypes(BindingFlags.Public)
        .OrderBy(t => t.MetadataToken)
        .Select((type, index) => new { type, index })
        .ToDictionary(t => t.type, t => t.index);

    public static int GetIndex(Option<A> value)
    {
        return TypeIndices[value.GetType()];
    }

}

// Model definition for `dojo_examples::models::PlayerConfig` model
public class PlayerConfig : ModelInstance
{
    [ModelField("player")]
    public FieldElement player;

    [ModelField("name")]
    public string name;

    [ModelField("items")]
    public PlayerItem[] items;

    [ModelField("favorite_item")]
    public Option<uint> favorite_item;

    // Start is called before the first frame update
    void Start()
    {
        Debug.Log(JsonConvert.SerializeObject(new TypedData(Model)));
    }

    // Update is called once per frame
    void Update()
    {
    }
}
