// Generated by dojo-bindgen on Mon, 8 Jul 2024 11:09:54 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace flippyflop {
    // Model definition for `dojo_examples::models::Message` model
    public class Tile : ModelInstance {
        [ModelField("x")]
        public uint x;

        [ModelField("y")]
        public uint y;

        [ModelField("flipped")]
        public FieldElement flipped;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        